ALTER TABLE invitations MODIFY accomodations TEXT;
ALTER TABLE invitations ADD friday BOOLEAN DEFAULT NULL;
ALTER TABLE invitations ADD saturday BOOLEAN DEFAULT NULL;
ALTER TABLE invitations ADD sunday BOOLEAN DEFAULT NULL;
