INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (1,  FALSE, 'Steve Gerhat', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (1,  FALSE, 'Brenda Gerhat', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (2,  FALSE, 'Leslie Gerhat', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (2,  FALSE, 'Zachary Newell', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (3,  FALSE, 'Brandon Gerhat', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (3,  TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (4,  FALSE, 'Nikki McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (4,  FALSE, 'Joseph McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (4,  FALSE, 'LauraAnn McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (4,  FALSE, 'Calli McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (4,  FALSE, 'Kieran McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (5,  FALSE, 'Chelsea McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (5,  TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (6,  FALSE, 'David McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (6,  FALSE, 'Katie McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (7,  FALSE, 'Michael McDevitt', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (7,  TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (8,  FALSE, 'Michael Ryan', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (8,  TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (9,  FALSE, 'Christopher Ryan', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (9,  TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (10, FALSE, 'Luke Aziz', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (10, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (11, FALSE, 'AJ Rasheed', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (11, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (12, FALSE, 'Shawn Fiedler', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (12, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (13, FALSE, 'Samuel Strong', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (13, FALSE, 'Sara Moyer', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (14, FALSE, 'Jesse Miner', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (14, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (15, FALSE, 'Jackie Davis', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (15, FALSE, 'James Davis', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (16, FALSE, 'Katie Hoban', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (16, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (17, FALSE, 'Kathy Fox', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (17, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (18, FALSE, 'Linda Szmal', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (18, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (19, FALSE, 'Dustin Simeone', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (19, TRUE,  'Guest', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (20, FALSE, 'Kiki Ray', NULL, NULL);
INSERT INTO guests (invitationId, isGuest, name, attending, entree) VALUES (20, TRUE,  'Guest', NULL, NULL);
